
services:
  client1:
    build: ./client
    networks: [wormnet]
    hostname: client1

  client2:
    build: ./client
    networks: [wormnet]
    hostname: client2

  worm:
    build: ./worm
    networks: [wormnet]
    depends_on: [client1, client2]

networks:
  wormnet:
    driver: bridge
